name: Build

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build and test mixxx-folders2crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          # In order:
          # * Go module download cache
          # * Go build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ubuntu-latest-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ubuntu-latest-go-

      - name: Run tests
        run: go test -v ./...

      - name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
