name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release mixxx-folders2crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          # In order:
          # * Go module download cache
          # * Go build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ubuntu-latest-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ubuntu-latest-go-

      - name: Run tests
        run: go test -v ./...

      - name: Build & release to GitHub
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
